Algoritmo "Questão01"
// Desenvolver um programa que pergunte ao usuário o seu nome completo
//e seu sexo. Em seguida, o programa deve apresentar os dados
//anteriormente informados.

Var
// Seção de Declarações das variáveis 

nome, sexo: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Qual o seu nome completo? ")
leia(nome)

escreva("Informe o seu sexo ")
leia(sexo)


escreva("Olá ",nome,", muito prazer! O sexo informado é " ,sexo,".")

Fimalgoritmo